# Generated by Django 3.0.5 on 2020-05-07 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('standards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('admission_no', models.CharField(max_length=20)),
                ('father', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=210, null=True)),
                ('caste', models.CharField(choices=[('BC', 'BC'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST'), ('General', 'General'), ('Other', 'Other')], default='General', max_length=20)),
                ('religion', models.CharField(choices=[('Hindu', 'Hindu'), ('Muslim', 'Muslim'), ('Christian', 'Christian'), ('Other', 'Other')], default='Hindu', max_length=10)),
                ('current_standard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Class', to='standards.Standard')),
                ('standards', models.ManyToManyField(to='standards.Standard')),
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
