# Generated by Django 3.0.5 on 2020-05-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(default='s@gmail.com', max_length=255, unique=True)),
                ('contact_no', models.CharField(blank=True, max_length=10)),
                ('first_name', models.CharField(default='s', max_length=200)),
                ('last_name', models.CharField(default='0', max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('is_student', models.BooleanField(default=True)),
                ('is_teacher', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('address', models.CharField(blank=True, default='', max_length=200)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/')),
                ('date_of_birth', models.DateField(blank=True, help_text='Format: YYYY-MM-DD', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
