# Generated by Django 3.0.3 on 2020-07-25 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_auto_20200726_0230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='is_class_teacher',
        ),
    ]
