# Generated by Django 3.0.5 on 2020-05-07 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
        ('standards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_marks', models.PositiveIntegerField(blank=True, default=100, null=True)),
                ('classes_per_week', models.PositiveIntegerField(blank=True, default=6, null=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=210, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.SubjectName')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='standards.Standard')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.Teacher')),
            ],
        ),
    ]
