# Generated by Django 3.0.5 on 2020-05-07 15:54

from django.db import migrations, models
import django.db.models.deletion
import uploads.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Assignment', 'Assignment'), ('Notice', 'Notice'), ('Announcement', 'Announcement'), ('Reference', 'Reference'), ('Marksheet', 'Marksheet')], default='Assignment', max_length=20)),
                ('pdf', models.FileField(upload_to='uploads/', validators=[uploads.validators.validate_file_extension])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.Subject')),
            ],
        ),
    ]
