# Generated by Django 3.0.3 on 2020-07-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=210, null=True),
        ),
    ]
