# Generated by Django 3.0.3 on 2020-07-25 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classteacher',
            name='standard',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='standards.Standard'),
        ),
    ]
