# Generated by Django 3.0.3 on 2020-07-25 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0002_auto_20200725_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classteacher',
            name='standard',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='class_teacher', to='standards.Standard'),
        ),
    ]
