# Generated by Django 3.0.3 on 2020-07-25 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0003_auto_20200725_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classteacher',
            name='standard',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_teacher', to='standards.Standard'),
        ),
    ]
