# Generated by Django 3.0.3 on 2020-07-25 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_auto_20200726_0230'),
        ('standards', '0004_auto_20200725_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_teacher', to='teachers.Teacher'),
        ),
    ]
